# Upon creating a new release, a depot entry will be created that updates

name: Populate Depot json

on: 
  # runs when this repository's releases are modified
  release: 
  # allows for manual dispatching of the workflow
  workflow_dispatch: 

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions: 
      # permits reading of releases and writing to the depot branch
      contents: write
    steps:
        # where to find gh action and what version to use
      - uses: LemLib/pros-depot@v0.1.0-beta.1
        with:
          # gives the github action the permissions specified above
          token: ${{ github.token }}
          # target repo for depots
          repo: ${{ github.repository }}
          # where to read releases from (can be omitted if repo is also the repo from which to read releases from, but it doesn't sem to be working at the moment)
          source-repo: ${{ github.repository }}
          # The branch where the stable depot json will be placed.
          branch: depot
          # The branch of the depot where pre release versions should be placed. 
          pre-release-branch: depot
          # The path to the stable depot json.
          path: stable.json
          # The path to the depot where pre release versions should be placed. 
          pre-release-path: beta.json
          # The commit message that will be used when updating the depot.
          # If ommited then a auto-generated commit message will be used. 
          # message: "Update depot"
          
          # makes the json output human readable (formatting)
          readable-json: true
