
name: Build Template

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README with the latest links
        run: |
          echo "\n## [Github link](${{github.server_url}}/${{github.repository}})" >> README.md
          perl -i -pe 's@(?<=[^/])(docs/assets/.*?)(?=[")])@${{github.server_url}}/${{github.repository}}/blob/master/$1?raw=true@g' README.md

      - name: Run LemLib/pros-build
        id: test
        uses: LemLib/pros-build@v2.0.1
        with:
          copy_readme_and_license_to_include: true
          lib_folder_name: <<LIB_FOLDER_NAME>>

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
          path: ${{ github.workspace }}/template/*
