# Runs a format check on all pull requests and pushes.

name: test-clang-format

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './src/ ./include/<<LIB_FOLDER_NAME>>'
        extensions: 'hpp,cpp'
        clangFormatVersion: 17
